services:
    postgres:
        image: postgres:15
        container_name: bfa-postgres-db
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./initdb:/docker-entrypoint-initdb.d 
        ports:
          - "15432:5432"
        networks:
          - bfa-net
    # bot:
    #   build: .
    #   restart: always
    #   env_file:
    #     - .env
    #   depends_on:
    #     - postgres
    #   networks:
    #     - bfa-net

volumes:
  pgdata:

networks:
  bfa-net: